name: Bug Report - Text Based
description: File a bug report using text and code outputs.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat

body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: country
    attributes:
      label: Country Name
      description: What is the name of the country in which you found this issue?
      placeholder: ex. use the iso code name for example COL is the ISO code for Colombia.
    validations:
      required: True

  - type: input
    id: Year
    attributes:
      label: Years of occurrence
      description: What is the year of this issue?
      placeholder: ex. 1990 and 1996.
    validations:
      required: True

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant code
      description: Please copy and paste any relevant code output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/worldbank/gld/blob/main/Support/E%20-%20Community%20Guidelines/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
